### ISSUE TITLE
About 4GB Decoding

### ISSUE THREAD

**Issue by WY-WY-W** [superbboy/Lenovo-XIAOXIN-14-2019-IWL-Hackintosh#1]
想请问一下，About 4GB Decoding在Bios的哪里？找了很久了。是一样的笔记本，谢谢ヾ(≧▽≦*)o

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。

**Comment by superbboy** [comment]
BIOS没有就不管，以前用Thinkpad T460s做黑果也没有处理过这个。
